HTML-32 - Repeat string
easycodeguides/html pull request #15
Opened 2020-01-28 10:10 UTC by burmazovic

Repeat input string specified number of times.

2020-01-28 18:05 UTC, ban17 requested changes

2020-01-28 18:05 UTC, ban17 commented on html-32/HTML-32.js
> +submitButton.addEventListener("click",
You need to get "form" tag and addEventListener "submit"

2020-01-28 18:05 UTC, ban17 commented on html-32/HTML-32.js
> +    let words = [];
words=''

2020-01-28 18:05 UTC, ban17 commented on html-32/HTML-32.js
> +    return words.toString();
return words

2020-01-30 21:35 UTC, hanii1993 approved these changes

2020-01-30 21:39 UTC, ban17 approved these changes

2020-01-31 06:52 UTC, merged