Html 4 - Borders on the calendar, text aligned
easycodeguides/html pull request #17
Opened 2020-02-15 02:22 UTC by FilipHusidic

Napravio tabelu, zavrsio kalendar i postavio 'borders', non-collapsed, text centriran

2020-02-15 11:46 UTC, ban17 commented on HTML-4/table.html
> +</html>
Always add one empty line at the end of file.

2020-02-15 11:46 UTC, ban17 requested changes
Just delete that empty file if you are not using it.

2020-02-18 19:14 UTC, ban17 approved these changes

2020-02-18 19:14 UTC, hanii1993 approved these changes

2020-02-19 00:33 UTC, FilipHusidic reviewed
I've deleted the unnecessary file and added an extra line at the end of the table.html file.

2020-02-19 00:35 UTC, merged