Mainpage
easycodeguides/html pull request #3
Opened 2020-01-21 14:34 UTC by hanibane

* Added navigations to main-page.html

2020-01-21 14:52 UTC, ban17 requested changes

2020-01-21 14:52 UTC, ban17 commented on style.css
> +nav > ul li > a{ padding:15px 100px; text-decoration:none; color:#fff; background:#267326; }
maybe selector can be `nav a`

2020-01-21 18:24 UTC, ban17 requested changes

2020-01-21 18:24 UTC, ban17 commented on main-page.html
> +    var oddNumbers = document.getElementById('odd-numbers').addEventListener('click',oddNumberClick);
Use let or const, avoid var.

2020-01-21 18:24 UTC, ban17 commented on main-page.html
> +        script.type = 'text/javascript';
redundant - type text/javascript is default and not needed anymore

2020-01-21 18:24 UTC, ban17 commented on main-page.html
> +</html>
set in editor to add new line always

2020-01-21 18:24 UTC, ban17 commented on main-page.html
> +
avoid adding blank lines randomly

2020-01-21 18:24 UTC, ban17 commented on main-page.html
> +        <li id="even-numbers"><button>Even Numbers</button></li>
Why this is button tag?

2020-01-21 18:24 UTC, ban17 commented on main-page.html
> +    let jsLists = document.getElementById('javascript-lists');
This need to be inside function openJS

2020-01-21 18:24 UTC, ban17 commented on main-page.html
> +    clickJS.addEventListener('click',openJS);
clickJS is used just once and can be written inline:
`document.getElementById('click-javascript').addEventListener('click',openJS);

2020-01-21 18:24 UTC, ban17 commented on main-page.html
> +    var oddNumbers = document.getElementById('odd-numbers').addEventListener('click',oddNumberClick);
also remove `var oddNumbers` part it's not used

2020-01-23 18:49 UTC, ban17 commented on main-page.html
> +        <li><a>CSS-grid</a></li>
Link must have href.

2020-01-23 18:52 UTC, ban17 requested changes
Add href to all links or make them normal text.

2020-01-23 20:35 UTC, janko1031 approved these changes
everything fine for me now.

2020-01-25 16:16 UTC, ban17 requested changes

2020-01-25 16:16 UTC, ban17 commented on main-page.html
> +        <li id="html-17"><a>HTML-17 - Simple Prompt</a></li>
You should use href here too.

2020-01-25 16:16 UTC, ban17 commented on main.js
> +
remove redundant blank lines

2020-01-25 16:16 UTC, ban17 commented on style.css
> +
This line need to be empty (no spaces).

2020-01-25 16:21 UTC, ban17 approved these changes

2020-01-25 16:22 UTC, merged