HTML-16 - evenNumbers
easycodeguides/html pull request #4
Opened 2020-01-21 15:54 UTC by zeljkosoko

2020-01-21 15:59 UTC, hanii1993 requested changes

2020-01-21 15:59 UTC, hanibane commented on evenNumbers.js
> +console.log(nums);
Add new line

2020-01-21 16:12 UTC, zeljkosoko commented on evenNumbers.js
> +console.log(nums);
New empty line at the end?

2020-01-21 16:21 UTC, hanibane commented on evenNumbers.js
> +console.log(nums);
yes

2020-01-22 09:00 UTC, zeljkosoko commented on evenNumbers.js
> +console.log(nums);
empty lines added.

2020-01-22 09:41 UTC, hanii1993 approved these changes

2020-01-22 09:59 UTC, ban17 approved these changes

2020-01-22 10:09 UTC, merged