HTML-19 Change to capital letters or small letters
easycodeguides/html pull request #5
Opened 2020-01-21 19:18 UTC by burmazovic

I have wrote the function preslovi().
Function is going thru each character and if it is a lower it is changing it to upper case, and vice versa.

2020-01-21 20:26 UTC, Iwana279 commented on HTML-19/HTML-19.js
> +
Ne treba stavljati bespotrebno toliko praznih redova.

2020-01-21 20:26 UTC, ZivojnovicZarko commented on HTML-19/HTML-19.js
> +let ispisPolje = document.getElementById("ispisPolje");
Please use english for variable and function naming. Also for ids and classes.

2020-01-21 20:34 UTC, ZivojnovicZarko commented on HTML-19/index.html
> +	<p>
Use label instead of `p` tag for text related to input.

2020-01-21 20:36 UTC, ZivojnovicZarko commented on HTML-19/index.html
> +		<button id="submit" type="submit" value="Click me!">
This button has no text, it should be 
```
<button id="submit" type="submit">Click me!</button>
```

2020-01-21 20:37 UTC, ZivojnovicZarko commented on HTML-19/HTML-19.js
> +        ispisPolje.innerText = ispis;
In this case you're going to print an array of the characters, it should be 
`ispisPolje.innerText = ispis.join('');`

2020-01-22 15:57 UTC, hanii1993 approved these changes

2020-01-22 16:07 UTC, ban17 approved these changes

2020-01-22 16:07 UTC, ban17 commented on HTML-19/index.html
> +	<p id="ispisPolje"></p>
Mogao bi ovaj indent malo da središ ;)

2020-01-22 16:07 UTC, ban17 commented on HTML-19/index.html
> +	<p id="ispisPolje"></p>
Ako već praviš nešto sa submit dugmetom fino bi bilo da sve to okružiš formom a event listener da bude submit na tu formu a ne click na dugme.

2020-01-22 16:08 UTC, ban17 requested changes

2020-01-22 16:08 UTC, ban17 commented on HTML-19/index.html
> +	<label for="input">Insert words:</label>
Form still missing.

2020-01-23 18:46 UTC, ban17 approved these changes

2020-01-23 20:43 UTC, janko1031 commented on HTML-19/HTML-19.js
> +}
there should be one new line at the end of file.

2020-01-23 20:43 UTC, janko1031 commented on HTML-19/index.html
> +</html>
same here, new line should be here.

2020-01-25 07:09 UTC, merged